version: '3.8'
services:
  opnsense_wg_um:
    container_name: opnsense_wg_um
    image: opnsense_wg_um
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/home/app/web/staticfiles
    networks:
      - web_network
    depends_on: 
      - opnsense_wg_um
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 