# Generated by Django 4.2 on 2023-04-17 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wg_users", "0005_alter_wireguardconfig_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wireguardconfig",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
