# Generated by Django 4.2 on 2023-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WireguardConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("wg_user_uuid", models.UUIDField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("private_key", models.CharField(max_length=1000)),
                ("public_key", models.CharField(max_length=1000)),
                ("server_public_key", models.CharField(max_length=1000)),
                ("server_endpoint", models.CharField(max_length=100)),
                ("server_endpoint_port", models.IntegerField()),
                ("server_allowed_ips", models.CharField(max_length=1000)),
                ("persistent_keepalive", models.IntegerField()),
                ("dns", models.CharField(max_length=100)),
            ],
        ),
    ]
