# Generated by Django 4.2 on 2023-04-17 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wg_users", "0002_allowedipsgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedipsgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="allowedipsgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
