# Generated by Django 4.2 on 2023-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wg_users", "0003_allowedipsgroup_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowedipsgroup",
            name="allowed_ips_calculated",
            field=models.CharField(max_length=1000),
        ),
    ]
