name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: ${context}/Dockerfile.prod-nginx
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/opnsense-wg-um-ci
          tag: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/push-action@v2
        with:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/opnsense-wg-um-ci
          tag: latest
